import httpx
import uuid

BASE = "http://127.0.0.1:8000"


def test_register_login_and_submit_complaint():
    email = f"test+{uuid.uuid4().hex[:8]}@example.com"
    password = "TestPass123!"

    # Register
    r = httpx.post(f"{BASE}/api/auth/register", json={
        "email": email,
        "full_name": "E2E Tester",
        "password": password,
    }, timeout=10.0)
    assert r.status_code in (200, 201), f"register failed: {r.status_code} {r.text}"

    # Login (token)
    r2 = httpx.post(f"{BASE}/api/auth/token", data={
        "username": email,
        "password": password,
    }, headers={"Content-Type": "application/x-www-form-urlencoded"}, timeout=10.0)
    assert r2.status_code == 200, f"token failed: {r2.status_code} {r2.text}"
    token = r2.json().get("access_token")
    assert token, "no access_token returned"

    headers = {"Authorization": f"Bearer {token}"}

    # Submit a complaint
    payload = {
        "title": "E2E Test Complaint",
        "description": "This is a test complaint generated by E2E test.",
        "latitude": 0.0,
        "longitude": 0.0,
    }
    r3 = httpx.post(f"{BASE}/api/complaints", json=payload, headers=headers, timeout=10.0)
    assert r3.status_code in (200, 201), f"create complaint failed: {r3.status_code} {r3.text}"
